export const deploymentProgressContract={
 version:'1.1.0',uri:'plastic://schema/1/progress',
 transport:'Every persisted deployment event is published as eventType=deployment.progress on graph-notify-<graphId> and appended to observations.watch with the same event ID, sequence and diagnostic content. Socket delivery is best effort. Publication uses a durable outbox; duplicates are possible.',
 authorization:'Graph-scoped graph:read and iac:read-status are required for status/history/events and socket diagnostics. observations.watch also requires graph:observe. Delegations are resolved against the requested graph. An operation ID or cursor never grants access to another graph.',
 schema:{type:'object',required:['schemaVersion','eventType','id','kind','provenance','graphId','nodeId','operationId','correlationId','revisionId','inputDigest','sequence','at','receivedAt','source','phase'],properties:{
  schemaVersion:{const:1},eventType:{const:'deployment.progress'},provenance:{const:'server'},id:{type:'string',description:'Stable deduplication ID; identical AWS events keep the same ID across collection and retransmission.'},kind:{type:'string',description:'deployment.<state>, deployment.resource, deployment.stack, deployment.change-set, deployment.exception, deployment.orchestration, deployment.cleanup, deployment.log or deployment.diagnostic-warning.'},
  graphId:{type:'string'},nodeId:{type:'string'},operationId:{type:'string'},correlationId:{type:'string'},revisionId:{type:'string',description:'Accepted revision when the live content matches it; otherwise live. Legacy operations without a recorded revision use unknown, never a guessed revision.'},inputDigest:{type:'string'},reviewDigest:{type:['string','null']},sequence:{type:'integer',minimum:1},at:{type:'string',format:'date-time'},receivedAt:{type:'string',format:'date-time'},arrival:{type:'integer',description:'Graph-wide observations.watch arrival sequence.'},
  source:{enum:['worker','cloudformation','changeset','orchestration','cloudwatch','diagnostics','lifecycle','application']},phase:{enum:['planning','guardrails','awaiting-approval','deploying','rolling-back','cleanup','terminal','recovering','awaiting-recovery-approval','maintenance','readiness','runtime']},state:{type:'string'},status:{type:'string'},reason:{type:'string'},code:{type:'string'},stackName:{type:'string'},logicalId:{type:'string'},physicalId:{type:'string'},resourceType:{type:'string'},executionArn:{type:'string'},requestId:{type:'string'},logGroup:{type:'string'},logStream:{type:'string'},message:{type:'string'},truncated:{type:'boolean'},
  executionId:{type:'string'},lifecycle:{type:'object',description:'Structured lifecycle record; inspection, plan/approval/action/result, maintenance, invocation correlation or readiness. See plastic://schema/1/lifecycle.'},
  error:{type:'object',properties:{code:{type:'string'},message:{type:'string'},requestId:{type:'string'},trace:{type:'array',maxItems:6,items:{type:'string'}}}},recovery:{type:'object',properties:{category:{enum:['platform-intervention','template-correction','retry-review']},retryable:{type:'boolean'},message:{type:'string'}}}},additionalProperties:false},
 recovery:'Call iac.status to refresh current diagnostics and obtain progress.history and progress.watch references. Read iac.events from its graph/node/operation-bound cursor, then repeat with nextCursor, including after empty polls. Sequence uses arrival order, not the AWS timestamp, so late events remain visible. Deduplicate by id. iac.history lists previous operations; iac.status accepts operationId for historical inspection. Longer diagnostic pages are bounded to 100 events/120 KB. Use iac.events if the graph-wide watch replay window has expired.',
 sources:'The collector reads only the operation’s application and platform guardrail stacks, its exact Step Functions execution, and operation-correlated lines from the platform deployment worker log group. It never reads application Lambda log groups, outputs, request bodies, CloudFormation ResourceProperties, or workflow input/output. Collection errors are diagnostic-warning events and never replace the original exception.',
 bounds:'CloudFormation collection reads at most four pages per stack per refresh; orchestration reads at most 300 events per refresh. Both resume older pages on subsequent status/worker refreshes while always checking the newest page. progress.collectionPending identifies a backlog. AWS collection has an 18-second time budget and partial failures become warnings. Logs are a redacted tail of at most 20 entries from at most 100 matching entries in a five-minute operation window. Truncation and unavailable sources are explicit. Legacy log lines without operation correlation are excluded. No logs:Unmask permission is granted. Status resource summaries are bounded to 120 KB; resourceCount/resourcesTruncated identify further resources available through iac.events.',
 pages:{schema:{type:'object',required:['operationId','events','nextCursor','hasMore','receivedThrough'],properties:{operationId:{type:'string'},events:{type:'array',maxItems:100,items:{$ref:'plastic://schema/1/progress#/schema'}},nextCursor:{type:'string'},hasMore:{type:'boolean'},receivedThrough:{type:'integer'}}},meaning:'iac.events returns this page. nextCursor advances by server arrival sequence, including when AWS timestamps are older. Use the same cursor on the next poll even when events is empty.'},
 status:{fields:{state:'Review lifecycle state. Orchestration failure overrides a stranded nonterminal state; workflowState retains that recorded state.',approval:'Present only after a human approved reviewDigest; never implied by progress.',error:'Bounded original worker exception or preferred resource error.',reason:'Actionable resource/worker failure, ahead of secondary rollback/diagnostic errors.',recovery:'category, retryable, message',progress:'version, sequence, phase, latest, failure, failures, cleanup, applicationStack, resources, resourceCount, resourcesTruncated, collectedAt, collectionPending, collectionWarning, history, watch'},exampleCalls:[{tool:'iac.status',arguments:{schemaVersion:1,graphId:'example-graph',nodeId:'stack'}},{tool:'observations.watch',arguments:{schemaVersion:1,graphId:'example-graph',filter:{operationId:'01M4CSD7D7H7YM2HKY2Z5AJRHZ'}}},{tool:'iac.events',arguments:{schemaVersion:1,graphId:'example-graph',nodeId:'stack',operationId:'01M4CSD7D7H7YM2HKY2Z5AJRHZ',cursor:'<previous nextCursor>',limit:50}},{tool:'iac.history',arguments:{schemaVersion:1,graphId:'example-graph',nodeId:'stack'}}]},
 approval:'Graph acceptance, deployment approval and deployment completion are separate. Observing, reconnecting, refreshing or reading history never approves, retries or deploys. A new or corrected template requires a new plan and exact-digest human approval. Failed guardrails or uncertain cleanup use iac.inspect and iac.recovery.plan. Shared IAM prerequisites use iac.maintenance.request and a separate platform-admin review. See plastic://schema/1/lifecycle.',
 example:{schemaVersion:1,eventType:'deployment.progress',provenance:'server',id:'deployment:<operationId>:<stable-hash>',kind:'deployment.resource',graphId:'example-graph',nodeId:'stack',operationId:'01M4CSD7D7H7YM2HKY2Z5AJRHZ',correlationId:'01M4CSD7D7H7YM2HKY2Z5AJRHZ',revisionId:'rev_<accepted-revision>',inputDigest:'<reviewed-input-sha256>',reviewDigest:null,sequence:5,at:'2026-10-08T03:37:50.000Z',receivedAt:'2026-10-08T03:37:51.000Z',source:'cloudformation',phase:'guardrails',stackName:'graph-guardrails-<assigned-namespace>',logicalId:'WorkerRole',resourceType:'AWS::IAM::Role',status:'CREATE_FAILED',reason:'The platform guardrail role is not authorized to perform iam:GetRole on the assigned worker role.'},
};
