import * as z from 'zod/v4';
const ID=z.string().regex(/^[A-Za-z0-9_.-]{1,64}$/),ULID=z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);
const base={schemaVersion:z.literal(1),graphId:ID,nodeId:ID};
export const deploymentReviewSchema=z.object({...base,agentSessionId:ID.optional(),replace:z.boolean().optional(),action:z.enum(['apply','destroy']).optional(),retryOf:ULID.optional(),preservation:z.literal('strict').optional()}).strict();
const prerequisite=z.object({code:z.string(),kind:z.string(),message:z.string()}).passthrough();
const resource=z.object({logicalId:z.string(),resourceType:z.string(),physicalId:z.string().optional(),physicalIdentity:z.string().optional(),status:z.string(),deletionPolicy:z.string(),definitionDigest:z.string(),ownershipVerified:z.boolean(),exists:z.union([z.boolean(),z.literal('unknown')]).optional(),orphaned:z.boolean().optional()}).passthrough();
const stack=z.object({name:z.string(),status:z.string(),ownership:z.enum(['verified','unverified','absent']),stackId:z.string().optional(),lastStackId:z.string().optional(),resources:z.array(resource)}).passthrough();
const nextActions=z.object({retryable:z.boolean(),automaticRetry:z.literal(false),blockingPrerequisites:z.array(prerequisite),actions:z.array(z.object({tool:z.string().optional(),action:z.string().optional(),allowed:z.boolean(),requiredApproval:z.string().nullable(),reason:z.string().optional()}).passthrough())});
const maintenanceConfiguration=z.object({configured:z.boolean(),mode:z.literal('record-and-verify-only'),executesAws:z.literal(false),approvalEffect:z.string(),administratorRequirement:z.string(),blocker:prerequisite.optional()}).passthrough();
const recoveryReadiness=z.object({state:z.enum(['review-available','blocked','not-required']),prerequisites:z.array(prerequisite),missingRoles:z.array(z.string()),executionAuthority:z.string(),requiredApproval:z.literal('human-exact-recovery-digest'),requiresPlatformAdmin:z.boolean()});
const inspection=z.object({version:z.number(),checkedAt:z.string(),graphId:ID,nodeId:ID,
 application:stack,guardrail:stack,
 roles:z.array(z.object({logicalId:z.string(),arn:z.string(),exists:z.union([z.boolean(),z.literal('unknown')]),matches:z.boolean()}).passthrough()),
 boundary:z.object({arn:z.string(),exists:z.union([z.boolean(),z.literal('unknown')])}).passthrough(),
 recoveryReadiness,blockers:z.array(prerequisite),canReview:z.boolean(),
 awsVerification:z.object({kind:z.literal('actual-read-and-assume-calls'),deploymentTested:z.literal(false),checks:z.array(z.object({component:z.string(),action:z.string(),resource:z.string(),result:z.enum(['succeeded','absent','failed']),code:z.string().optional(),error:z.any().optional()}).passthrough())}),
 applicationRoleLifecycle:z.object({kind:z.literal('document-analysis-and-physical-role-reads'),executionRoleArn:z.string(),deploymentTested:z.literal(false),limitations:z.string(),roles:z.array(z.object({logicalId:z.string(),name:z.string(),expectedArn:z.string(),actualArn:z.string().nullable(),exists:z.union([z.boolean(),z.literal('unknown')]),cloudFormationStatus:z.string(),checks:z.array(z.object({phase:z.enum(['before-creation','path-scoped-lifecycle']),action:z.string(),resource:z.string(),result:z.enum(['allowed-by-document','explicit-deny','conditional-or-unknown','not-granted','unavailable'])}))}))}).optional(),
 maintenanceConfiguration:maintenanceConfiguration.optional(),historicalFailure:z.any().optional(),historyIsNotCurrentPermissionEvidence:z.literal(true).optional(),
}).passthrough();
const recoveryReview=z.object({version:z.string(),digest:z.string().regex(/^[a-f0-9]{64}$/).nullable(),preservation:z.literal('strict').optional(),sourceOperationId:ULID,graphId:ID,nodeId:ID,
 preservesData:z.boolean(),prerequisites:z.array(prerequisite),ownershipEvidence:z.object({application:stack,guardrail:stack}),
 actions:z.array(z.object({kind:z.enum(['delete-stack','import-retained','reconcile-guardrails','continue-update-rollback','rollback-stack','release-operation']),target:z.enum(['guardrail','application','operation']),dataLoss:z.array(z.string()),retainIds:z.array(z.string()).optional(),preparation:z.object({kind:z.literal('owned-empty-stack'),templateDigest:z.string(),createsResources:z.literal(false),roleArn:z.string()}).optional(),resources:z.array(z.object({logicalId:z.string(),physicalId:z.string().optional(),physicalIdentity:z.string().optional(),resourceType:z.string().optional(),outcome:z.enum(['Already absent','Retain','Delete','Create from approved platform definition']).optional(),identifier:z.string().optional(),definitionDigest:z.string().optional()}).passthrough()).optional()}).passthrough()),
 approvalRequirements:z.object({kind:z.literal('infrastructure-recovery'),exactDigest:z.literal(true),platformAdministrator:z.literal(false),applicationDeployment:z.literal(false)}),approval:z.string(),
}).passthrough();
export const lifecycleResultSchemas={
 'iac.inspect':inspection.extend({operationId:ULID,nextActions}),
 'iac.recovery.plan':z.object({operationId:ULID,graphId:ID,nodeId:ID,action:z.literal('recover'),state:z.enum(['recovery-blocked','recovery-ready','recovery-requested','recovering','recovered','failed','cancelled']),recoveryPlan:recoveryReview,inspection,expiresAt:z.number(),nextActions}).passthrough(),
 'iac.cancel':z.object({operationId:ULID,graphId:ID,nodeId:ID,state:z.literal('cancelled'),reviewDigest:z.null(),reviewInvalidatedAt:z.number(),cancellation:z.object({at:z.number(),by:z.string(),priorState:z.string(),reason:z.string(),awsMutations:z.literal(false),invalidatedDigests:z.object({deployment:z.string().nullable(),recovery:z.string().nullable()}),retainedChangeSet:z.string().nullable()}),nextActions}).passthrough(),
 'iac.maintenance.request':z.object({digest:z.string(),state:z.string(),requirements:z.array(prerequisite),execution:z.object({mode:z.literal('record-and-verify-only'),executesAws:z.literal(false),approvalTriggersRelease:z.literal(false),recoveryApproved:z.literal(false),applicationDeploymentApproved:z.literal(false)}),administration:maintenanceConfiguration}).passthrough(),
};
export const lifecycleTools={
 'iac.cancel':{method:'cancel',write:true,description:'Cancel the expected current unapproved infrastructure review, including pending recovery and expired reviews. Graph-scoped iac:propose authority is required. Atomically invalidates approval and logically releases its own lock; idempotent retries finish owner-only fence cleanup and durable event publication. Never mutates AWS resources or stops planning/approved/executing work. Retains unexecuted change sets as inert evidence.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID,reason:z.string().max(400).optional()}).strict()},
 'iac.inspect':{method:'inspect',write:false,description:'Read current AWS stack/resource ownership, retained resources, role/trust/boundary documents, actual read/assumption results and active operations. Historical failures, template validation and policy analysis are separate evidence. Optional preservation=strict reports non-destructive readiness. Never deploys or recovers.',schema:z.object({...base,operationId:ULID.optional(),preservation:z.literal('strict').optional()}).strict()},
 'iac.recovery.plan':{method:'plan',write:true,description:'Prepare an immutable recovery plan for an isolated failed deployment. preservation=strict prohibits stack/resource deletion, replacement, data loss, and unverified rollback/import behavior, including guardrail work. Returns precise current-state blockers without destructive fallback. Idempotency key is required; nothing executes until a human approves the exact recovery digest in the graph. Recovery does not approve application deployment.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID,idempotencyKey:z.string().regex(/^[A-Za-z0-9_.-]{1,128}$/),allowDataLoss:z.boolean().optional(),preservation:z.literal('strict').optional()}).strict()},
 'iac.maintenance.request':{method:'maintenance',write:true,description:'Record a graph-visible request for current platform prerequisites. This is record-and-verify-only: neither requesting nor approving it executes AWS changes or triggers a platform release. The response explains missing PLATFORM_ADMIN_SUBS configuration. Ordinary graph recovery approval does not require platform-admin membership.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID}).strict()},
 'iac.runtime.logs':{method:'runtimeLogs',write:false,description:'Read bounded, redacted Lambda diagnostics for a logical function owned by an approved application stack. Window <=1 hour within 7 days; opaque cursors preserve filters. Same records are published to the graph bus and iac.events. Arbitrary console payloads and account-wide log access are excluded.',schema:z.object({...base,operationId:ULID.optional(),logicalId:z.string().regex(/^[A-Za-z0-9]{1,64}$/),startTime:z.iso.datetime().optional(),endTime:z.iso.datetime().optional(),invocationId:ULID.optional(),requestId:z.string().regex(/^[A-Za-z0-9_.:-]{1,128}$/).optional(),correlationId:z.string().regex(/^[A-Za-z0-9_.:-]{1,128}$/).optional(),cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(100).optional()}).strict()},
 'iac.readiness':{method:'readiness',write:true,description:'Run one readiness check declared in the approved deployment through graph.invoke. Requires graph execution authority. Reusing its idempotency key returns the existing run, never repeats side effects. Readiness is separate from deployment completion and multiplayer verification.',schema:z.object({...base,agentSessionId:ID.optional(),checkId:ID,idempotencyKey:z.string().regex(/^[A-Za-z0-9_.-]{1,128}$/)}).strict()},
};
export const lifecycleContract={
 uri:'plastic://schema/1/lifecycle',version:'1.3.0',
 resultSchemas:Object.fromEntries(Object.entries(lifecycleResultSchemas).map(([name,schema])=>[name,z.toJSONSchema(schema)])),
 tools:{'iac.review':{description:'Prepare a fresh exact-digest human deployment review, with optional strict preservation. Cancellation is separate and never repairs AWS state.',inputSchema:z.toJSONSchema(deploymentReviewSchema)},...Object.fromEntries(Object.entries(lifecycleTools).map(([name,tool])=>[name,{description:tool.description,inputSchema:{...z.toJSONSchema(tool.schema),...(name==='iac.runtime.logs'?{allOf:[{not:{required:['requestId','invocationId']}},{not:{required:['requestId','correlationId']}},{not:{required:['invocationId','correlationId']}}]}:{})}}]))},
 cancellation:{
  tool:'iac.cancel',permissions:['graph:read','iac:propose'],expectedIdentity:'graphId, nodeId and the current operationId are required. A different graph/node is not found; a superseded review is stale. Retrying an already-cancelled operation is safe even after a new operation starts.',
  eligible:['awaiting-review','recovery-ready','recovery-blocked','expired','stale'],excluded:'Any approval, worker execution/startup, planning state, or recovery dispatch makes this pending-review operation ineligible. It cannot stop AWS work. execution.cancel is a different graph-runtime contract.',
  atomicity:'One conditional write of the operation is the cancellation linearization point shared with approval. It sets state=cancelled, nulls deployment/recovery approval digests and makes the owned fence logically free. S3 does not provide multi-object transactions: owner-conditional physical fence cleanup and the durable progress outbox follow and are resumable through the same cancel call or iac.status. No later worker can execute the cancelled record, and cleanup cannot release another operation’s fence.',
  expiry:'An unapproved expired review remains cancellable. No worker must be alive to release its lock. A cancelled review must be replaced, never re-approved.',
  aws:'No AWS resource API is called. Unexecuted change sets remain as inert evidence; cancellation does not delete change sets, stacks, resources or data. Platform administrators with unrelated direct AWS access remain outside the graph approval boundary.',
  event:{kind:'deployment.review.cancelled',eventType:'deployment.progress',state:'cancelled',phase:'terminal',reviewDigest:null,lifecycle:{approvalValid:false,lockReleased:true,cancellation:{at:'Unix milliseconds',by:'authenticated subject',priorState:'recovery-ready',reason:'bounded redacted reason',awsMutations:false,invalidatedDigests:{deployment:null,recovery:'previous digest, now invalid'},retainedChangeSet:null}}},
  retry:'Cancellation releases review ownership only. iac.review can then reach fresh AWS readiness checks; it can still return RECOVERY_REQUIRED or PRESERVATION_BLOCKED. Historical evidence remains in iac.history and iac.events.',
 },
 preservation:{
  request:{preservation:'strict'},tools:['iac.inspect','iac.review','iac.recovery.plan'],binding:'The inspect option is advisory and does not set a review constraint. On review or recovery.plan the constraint is bound into the reviewed digest, inherited by subsequent reviews on this stack node, and rechecked by workers immediately before mutation. Omitting it cannot downgrade an existing strict operation. It is not approval, an IAM grant, or an automatic retry.',
  semantics:'Prohibit stack deletion, resource removal/replacement, uncertain replacements and deployment-induced data removal. Every application resource must declare DeletionPolicy: Retain and UpdateReplacePolicy: Retain. S3 lifecycle expiration, enabled TTL, introduced/shorter log retention, reduced queue retention, index removal and reduced recovery history are rejected. No bucket emptying, purge, import/delete workaround or failed-state rollback runs.',
  enforcement:'Current stack state and ownership are checked before preparatory guardrail work. Approved application changes are checked again against the actual change set and current template before execution. CloudFormation executes with DisableRollback=true; new resources remain after failure. Only verified in-place IAM role-policy/trust changes and additions are supported for guardrail reconciliation. Boundary document/version changes and unverified actions stop with an explicit blocker. Strict operations do not run AWS change-set cleanup.',
  limitations:'ROLLBACK_FAILED, ROLLBACK_COMPLETE and DELETE_FAILED cannot take an ordinary in-place update. Strict mode leaves these stacks intact and returns PRESERVATION_IN_PLACE_UNSUPPORTED with AWS documentation and non-executing alternatives. CREATE_FAILED, UPDATE_FAILED, UPDATE_ROLLBACK_FAILED and import/rollback paths return PRESERVATION_STATE_UNVERIFIED until the platform can prove a resource-preserving sequence; this is a platform verification limit, not a claim that AWS has no such APIs. Finite log-retention introduction is incompatible with strict preservation; the existing cost policy also rejects unbounded log groups. Use supported resources or request a separately reviewed generic retention capability, not a bypass.',
  scope:'Deployment/recovery effects only. This does not stop existing application traffic, existing TTL/retention processing, changes made by unrelated AWS administrators, or application code deliberately invoked outside deployment. It does not claim backups, indefinite SQS retention or runtime/business-data immutability.',
  error:{code:'PRESERVATION_BLOCKED',retryable:false,problems:[{code:'PRESERVATION_IN_PLACE_UNSUPPORTED',kind:'preservation',component:'guardrail',stackStatus:'ROLLBACK_FAILED',limitation:'aws-stack-state',message:'CloudFormation cannot ordinarily update this state; deletion is prohibited. Leave it intact or independently review a separate stack node.'}]},
 },
 automaticApproval:{enabledBy:'Explicit human opt-in with warning in the graph editor. Off by default; reset on reload or graph change. MCP cannot enable it or approve.',eligibility:'iac.status.automaticApproval reports allowed and reason. The server rejects approvalMode=automatic for stack deletion, resource removal/replacement, uncertain deployment changes, rollback recovery and any data loss. Only current unexpired exact digests can be approved.',audit:'approval.mode and recoveryApproval.mode identify manual or automatic approval in durable status and bus events. This mode does not accept graph proposals or create reviews.'},
 permissions:{inspect:['graph:read','iac:read-status'],plan:['graph:read','iac:propose'],recoveryApproval:'Authenticated human with graph read and iac:approve, through the graph UI; exact recovery digest required.',logs:['graph:read','iac:read-status','graph:observe','graph:inspect-payloads'],readiness:['graph:read','iac:read-status','graph:execute','graph:observe'],maintenanceReview:'Human with policy:admin whose verified sub is explicitly configured in PLATFORM_ADMIN_SUBS. Agents, delegations and ordinary graph ownership cannot grant platform administration.'},
 states:{recovery:['recovery-blocked','recovery-ready','recovery-requested','recovering','recovered','failed','cancelled'],maintenance:['requested','approved-awaiting-platform-release','verification-blocked','verified'],runtime:['pending','running','verified','failed'],deployment:'planning → awaiting-review → apply-requested → applying → succeeded/failed; unapproved awaiting-review/expired/stale can transition to cancelled.'},
 applicationRoleLifecycle:{inspection:'iac.inspect reads physical application roles separately from CloudFormation records. A DELETE_FAILED record can have exists=false; access-denied reads produce exists=unknown and block recovery.',permissions:'Existence probes before creation need name-only GetRole/GetRolePolicy within the assigned namespace. Creation, inline-policy writes/deletion and PassRole still require /graph-app/; mutation of root-path roles remains explicitly denied. Never treat a role name or CloudFormation record alone as evidence of a surviving role.',evidence:'applicationRoleLifecycle.checks analyze the currently installed execution policy, including explicit NotResource and NotAction denies. They are not AWS execution evidence. Actual GetRole checks run as the platform inspector. A new platform definition requires separately approved guardrail reconciliation for existing stacks; release does not change their policies automatically.'},
 evidence:{historical:'iac.status preserves the original failure even after permissions are corrected.',inspection:'iac.inspect reports checkedAt, current application/guardrail inventories and ownership evidence, current policy analysis, actual AWS read/STS calls, and the original workflow state.',policy:'Document analysis is not IAM simulation and neither is proof that CloudFormation will succeed. SCPs, session policies and service checks can deny real operations.',readiness:'A declared check node must assert application-specific health. The platform records completed execution, zero execution errors and zero denied effects. This does not prove real multiplayer behavior.'},
 recovery:{freshness:'Plans expire after 15 minutes. Digest binds source operation, namespace, template input digest, resource IDs/states/retention, approved guardrail definition, actions, prerequisites and data-loss choice. Observation timestamps and original error prose are excluded from the freshness fingerprint.',selection:'The following legacy actions require a review without strict preservation; strict mode blocks deletion/import/rollback and publishes explicit prerequisites. UPDATE_ROLLBACK_FAILED continues rollback without skipping resources. UPDATE_FAILED rolls back only with reviewed retention/data-loss implications. Failed creates/deletes remove only the owned failed stack, preserving retained data; RetainResources is used only for DELETE_FAILED. Retained resources are imported into the same namespace before names can be reused. import-retained.preparation discloses a fixed empty stack with no created resources: establish the assigned role and ownership tags first, then IMPORT without changing stack settings. Interrupted preparation preserves archived ownership evidence and needs a fresh approval; it does not silently discard retained names. Unsupported imports remain an explicit prerequisite.',isolation:'Guardrail templates come only from platform source. Imports require CloudFormation ownership evidence, not just matching names. Unrelated resources, shared deployment policies, extra role policies and unverified orphans cannot be changed by application recovery.',concurrency:'Deployment and recovery share one CAS stack fence. Duplicate recovery keys return the same operation; reuse for different input is refused. Worker leases plus deterministic AWS request tokens handle duplicate delivery. A stale plan or lost fence cannot execute.',retry:'No automatic retry of deterministic failures. After recovered, call iac.review with retryOf equal to the current recovery operation. Replacement operations retain previousOperationId and original evidence. Old approvals are invalidated. Human deployment approval itself triggers execution.'},
 incompleteGuardrails:{absence:'IAM NoSuchEntity/NoSuchEntityException means absent, independent of error wording. AccessDenied, network failures, timeouts and unsupported errors leave exists="unknown" and block recovery. Stack and workflow absence use their own documented service errors.',
  transientChecks:'Read-only inspection serializes IAM calls and retries transient throttling/transport failures with jitter, at most three attempts per call within the inspection deadline. Exhaustion returns AWS_CHECK_RETRYABLE, kind=transient, retryable=true and retryAfterMs; deadline exhaustion returns INSPECTION_INCOMPLETE. Readiness remains unverified, but these conditions alone do not require a platform administrator or a maintenance request. Wait, repeat iac.inspect, then prepare a fresh plan if needed. This does not retry a deployment or recovery mutation.',
  authority:'Only a separately approved review without strict preservation can request the legacy deletion/import path. An owned failed guardrail stack can be deleted and its retained boundary imported before platform-approved roles are recreated. These actions use the platform worker and guardrail service role, not the missing per-stack worker or execution role. Per-stack role assumption is verified after restoration.',
  preservation:'The plan lists already-absent roles separately from resources to delete and retained resources to import. IAM physical identities and boundary contents/consumers are rechecked before deleting or importing guardrails. Imported resources remain retained. In DELETE_FAILED only, confirmed-absent owned role records can be included in RetainResources to skip their deletion handlers; they are not imported as live resources. No arbitrary existing-resource adoption is supported.',
  limitation:'A stable guardrail stack with out-of-band deleted roles still recorded in its template returns GUARDRAIL_ROLE_RECREATE_UNSUPPORTED. An unchanged CloudFormation update cannot recreate those roles, and private repair has no CreateRole permission. A separately reviewed platform replacement procedure is required. Failed-creation recovery and boundary-only imports do not have this limitation.',
  approval:'Prepare a NEW iac.recovery.plan from the current operation with a new idempotencyKey after a platform fix; an existing blocked plan never silently becomes approved. A graph human with iac:approve reviews its exact digest. PLATFORM_ADMIN_SUBS is not required for ordinary graph-owned recovery.',
  evidence:'inspection.recoveryReadiness reports review-available/blocked/not-required, missingRoles, prerequisites, executionAuthority, requiredApproval and requiresPlatformAdmin. This describes recovery planning, not application deployability. historicalFailure and historicalFailureOperationId preserve old errors separately from current awsVerification.'},
 maintenance:{mode:'record-and-verify-only',executesAws:false,approvalTriggersRelease:false,
  bootstrap:'A platform administrator must review and deploy shared permission changes through the platform release process. PLATFORM_ADMIN_SUBS configures a separate human maintenance reviewer. Empty configuration returns PLATFORM_ADMIN_NOT_CONFIGURED in maintenanceConfiguration; graph ownership does not implicitly enable it. This configuration is not a prerequisite for graph-owned recovery.',
  approval:'A maintenance request and its human approval only record the reviewed prerequisite. An administrator releases any necessary platform change separately, then verifies current evidence in the graph. They never authorize recovery or application deployment.',
  response:{execution:{mode:'record-and-verify-only',executesAws:false,approvalTriggersRelease:false,recoveryApproved:false,applicationDeploymentApproved:false},administration:{configured:false,mode:'record-and-verify-only',executesAws:false,blocker:{code:'PLATFORM_ADMIN_NOT_CONFIGURED',kind:'configuration',component:'platform-authorization'}}}},
 resultFields:{inspection:{roles:'Array of {logicalId,arn,exists:true|false|"unknown",matches,policyDigest?,trustDigest?,boundary?}. Missing roles have exists=false; they are not permission denials.',recoveryReadiness:'{state:"review-available"|"blocked"|"not-required",prerequisites,missingRoles,executionAuthority,requiredApproval:"human-exact-recovery-digest",requiresPlatformAdmin}',awsVerification:'{kind:"actual-read-and-assume-calls",checks:[{component,action,resource,result:"succeeded"|"absent"|"failed",code?,error?}],deploymentTested:false}',maintenanceConfiguration:'{configured,mode:"record-and-verify-only",executesAws:false,approvalEffect,administratorRequirement,blocker?}'},
  recoveryPlan:{approvalRequirements:{kind:'infrastructure-recovery',exactDigest:true,platformAdministrator:false,applicationDeployment:false},actions:'Existing delete-stack/import-retained/reconcile-guardrails actions. Resource outcomes include "Already absent", "Retain", "Delete", and "Create from approved platform definition". An import includes physicalIdentity when AWS provides an immutable IAM identity.'}},
 observations:{transport:'deployment.progress records on the existing graph-notify bus, iac.events and observations.watch carry the same redacted lifecycle field. Status also includes nextActions, inspection, recoveryPlan, recoveryApproval, recoveryOutcomes, maintenance and runtimeReadiness. Existing cursors, stable IDs, outbox, deduplication and history apply.',fragmentation:'Reports above 14 KB use lifecycle.fragment={reportId,index,count,encoding:"base64-json-utf8",data}. Group by operationId and reportId; deduplicate index, order from zero, decode each base64 data value, concatenate the bytes, verify their SHA-256 equals reportId, and parse the UTF-8 JSON. At most 100 parts, each holding 10 KB of decoded bytes. Retain incomplete groups across reconnect and use iac.events to recover missing parts. This keeps graph WebSocket frames below 32 KB without discarding report content.',eventExtension:{source:['lifecycle','application'],phase:['recovering','awaiting-recovery-approval','maintenance','readiness','runtime'],lifecycle:'Structured inspection, recovery plan/approval/action/result, maintenance request/review, readiness result or invocation correlation, or a documented fragment of that record. No application payloads or credentials.',correlationId:'Deployment/recovery operation by default; application invocation uses its actual graph correlation ID.',executionId:'Present for graph invocation diagnostics.',requestId:'Lambda runtime request ID when available; lifecycle.bridgeRequestId links the private bridge invocation.'}},
 logs:{bounds:'100 raw events/page, 80 KB/page, one-hour time window, seven-day lookback, at most 100 pages/query, 24-hour cursor lifetime. AWS next tokens remain server-side. Empty pages can have a continuation. Omitted arbitrary console records and truncation are explicit. Choose at most one requestId, invocationId or correlationId filter; a cursor preserves that filter and window.',format:{type:'graph.application.diagnostic',level:'ERROR',requestId:'context.awsRequestId',correlationId:'event.context.correlationId',error:{code:'INVARIANT_FAILED',message:'Describe the failed invariant; never log inputs, tokens, or personal records.'}},limitations:'Lambda START/END/REPORT, runtime exceptions and the declared diagnostic record shape are supported. User console payloads are excluded. A call rejected before Lambda execution has no Lambda request ID and is diagnosed through invocation events.'},
 readinessDeclaration:{property:'node.properties.iac.readiness',example:[{id:'backend-health',nodeUrl:'backend-health',field:'in',value:{action:'health'},description:'The node calls the application bridge and throws if backend invariants fail.'}],approval:'Declarations are included in the input digest. Execute one named check per call; all declared checks must pass for runtimeReadiness.state=verified. Results include execution and revision references.'},
 examples:[
  {tool:'iac.cancel',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',operationId:'01M4C000000000000000000000',reason:'Discard this unapproved recovery; keep all existing stacks and data.'}},
  {tool:'iac.inspect',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',preservation:'strict'}},
  {tool:'iac.review',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',retryOf:'01M4C000000000000000000000',preservation:'strict'},note:'Cancellation is not recovery. If current AWS state forbids a preserving update, this returns structured blockers before worker startup.'},
  {tool:'iac.recovery.plan',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',operationId:'01M4C000000000000000000000',idempotencyKey:'preserve-1',preservation:'strict'},note:'Strict recovery never offers a delete-stack plan. Do not approve legacy destructive recovery to release its lock; use iac.cancel.'},
  {tool:'iac.inspect',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack'}},
  {result:{application:{status:'NOT_CREATED'},guardrail:{status:'ROLLBACK_FAILED',ownership:'verified'},roles:[{logicalId:'WorkerRole',exists:false,matches:false},{logicalId:'ExecutionRole',exists:false,matches:false}],boundary:{exists:true,matches:true},recoveryReadiness:{state:'review-available',missingRoles:['WorkerRole','ExecutionRole'],prerequisites:[],requiresPlatformAdmin:false},awsVerification:{kind:'actual-read-and-assume-calls',deploymentTested:false},canReview:false},note:'Missing roles are restored by approved recovery. canReview=false refers to application deployment; policy analysis is not evidence of successful AWS execution.'},
  {tool:'iac.recovery.plan',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',operationId:'01M4C000000000000000000000',idempotencyKey:'recovery-1'}},
  {human:'Open Recovery beside the CloudFormation notifications in the lower system bar, review the affected stack/resources, and approve its exact recovery digest.'},
  {tool:'iac.status',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack'}},
  {tool:'iac.review',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',retryOf:'<current recovered operation ID>'}},
  {human:'Approve the new exact deployment digest in the graph.'},
  {tool:'iac.runtime.logs',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',logicalId:'Backend',correlationId:'<graph invocation correlation>'}},
  {tool:'iac.readiness',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',checkId:'backend-health',idempotencyKey:'health-1'}},
 ],
};
