import * as z from 'zod/v4';
const ID=z.string().regex(/^[A-Za-z0-9_.-]{1,64}$/),ULID=z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);
const base={schemaVersion:z.literal(1),graphId:ID,nodeId:ID};
export const lifecycleTools={
 'iac.inspect':{method:'inspect',write:false,description:'Read current AWS stack/resource ownership, retained resources, role/trust/boundary documents, actual read/assumption results and active operations. Historical failures, template validation and policy analysis are separate evidence. Never deploys or recovers.',schema:z.object({...base,operationId:ULID.optional()}).strict()},
 'iac.recovery.plan':{method:'plan',write:true,description:'Prepare an immutable recovery plan for an isolated failed deployment. Ownership, retention and AWS state select the bounded actions. Idempotency key is required; nothing executes until a human approves the exact recovery digest in the graph. Recovery does not approve application deployment.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID,idempotencyKey:z.string().regex(/^[A-Za-z0-9_.-]{1,128}$/),allowDataLoss:z.boolean().optional()}).strict()},
 'iac.maintenance.request':{method:'maintenance',write:true,description:'Create a graph-visible request for current platform prerequisites. An explicitly configured human platform administrator reviews it separately. This tool never changes shared IAM or gives applications platform authority.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID}).strict()},
 'iac.runtime.logs':{method:'runtimeLogs',write:false,description:'Read bounded, redacted Lambda diagnostics for a logical function owned by an approved application stack. Window <=1 hour within 7 days; opaque cursors preserve filters. Same records are published to the graph bus and iac.events. Arbitrary console payloads and account-wide log access are excluded.',schema:z.object({...base,operationId:ULID.optional(),logicalId:z.string().regex(/^[A-Za-z0-9]{1,64}$/),startTime:z.iso.datetime().optional(),endTime:z.iso.datetime().optional(),invocationId:ULID.optional(),requestId:z.string().regex(/^[A-Za-z0-9_.:-]{1,128}$/).optional(),correlationId:z.string().regex(/^[A-Za-z0-9_.:-]{1,128}$/).optional(),cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(100).optional()}).strict()},
 'iac.readiness':{method:'readiness',write:true,description:'Run one readiness check declared in the approved deployment through graph.invoke. Requires graph execution authority. Reusing its idempotency key returns the existing run, never repeats side effects. Readiness is separate from deployment completion and multiplayer verification.',schema:z.object({...base,agentSessionId:ID.optional(),checkId:ID,idempotencyKey:z.string().regex(/^[A-Za-z0-9_.-]{1,128}$/)}).strict()},
};
export const lifecycleContract={
 uri:'plastic://schema/1/lifecycle',version:'1.0.0',
 tools:Object.fromEntries(Object.entries(lifecycleTools).map(([name,tool])=>[name,{description:tool.description,inputSchema:{...z.toJSONSchema(tool.schema),...(name==='iac.runtime.logs'?{allOf:[{not:{required:['requestId','invocationId']}},{not:{required:['requestId','correlationId']}},{not:{required:['invocationId','correlationId']}}]}:{})}}])),
 permissions:{inspect:['graph:read','iac:read-status'],plan:['graph:read','iac:propose'],recoveryApproval:'Authenticated human with graph read and iac:approve, through the graph UI; exact recovery digest required.',logs:['graph:read','iac:read-status','graph:observe','graph:inspect-payloads'],readiness:['graph:read','iac:read-status','graph:execute','graph:observe'],maintenanceReview:'Human with policy:admin whose verified sub is explicitly configured in PLATFORM_ADMIN_SUBS. Agents, delegations and ordinary graph ownership cannot grant platform administration.'},
 states:{recovery:['recovery-blocked','recovery-ready','recovery-requested','recovering','recovered','failed'],maintenance:['requested','approved-awaiting-platform-release','verification-blocked','verified'],runtime:['pending','running','verified','failed'],deployment:'Existing planning → awaiting-review → apply-requested → applying → succeeded/failed lifecycle remains separate.'},
 evidence:{historical:'iac.status preserves the original failure even after permissions are corrected.',inspection:'iac.inspect reports checkedAt, current application/guardrail inventories and ownership evidence, current policy analysis, actual AWS read/STS calls, and the original workflow state.',policy:'Document analysis is not IAM simulation and neither is proof that CloudFormation will succeed. SCPs, session policies and service checks can deny real operations.',readiness:'A declared check node must assert application-specific health. The platform records completed execution, zero execution errors and zero denied effects. This does not prove real multiplayer behavior.'},
 recovery:{freshness:'Plans expire after 15 minutes. Digest binds source operation, namespace, template input digest, resource IDs/states/retention, approved guardrail definition, actions, prerequisites and data-loss choice. Observation timestamps and original error prose are excluded from the freshness fingerprint.',selection:'UPDATE_ROLLBACK_FAILED continues rollback without skipping resources. UPDATE_FAILED rolls back only with reviewed retention/data-loss implications. Failed creates/deletes remove only the owned failed stack, preserving retained data; RetainResources is used only for DELETE_FAILED. Retained resources are imported into the same namespace before names can be reused. Unsupported imports remain an explicit prerequisite.',isolation:'Guardrail templates come only from platform source. Imports require CloudFormation ownership evidence, not just matching names. Unrelated resources, shared deployment policies, extra role policies and unverified orphans cannot be changed by application recovery.',concurrency:'Deployment and recovery share one CAS stack fence. Duplicate recovery keys return the same operation; reuse for different input is refused. Worker leases plus deterministic AWS request tokens handle duplicate delivery. A stale plan or lost fence cannot execute.',retry:'No automatic retry of deterministic failures. After recovered, call iac.review with retryOf equal to the current recovery operation. Replacement operations retain previousOperationId and original evidence. Old approvals are invalidated. Human deployment approval itself triggers execution.'},
 maintenance:{bootstrap:'A platform administrator must review and deploy the lifecycle worker permissions and configure PLATFORM_ADMIN_SUBS through platform CI. The graph records the request, separate administrator approval and fresh verification. It cannot edit shared IAM, authorize its own bootstrap, or mark an AWS permission fixed just because a request was approved.'},
 observations:{transport:'deployment.progress records on the existing graph-notify bus, iac.events and observations.watch carry the same redacted lifecycle field. Status also includes nextActions, inspection, recoveryPlan, recoveryApproval, recoveryOutcomes, maintenance and runtimeReadiness. Existing cursors, stable IDs, outbox, deduplication and history apply.',fragmentation:'Reports above 14 KB use lifecycle.fragment={reportId,index,count,encoding:"base64-json-utf8",data}. Group by operationId and reportId; deduplicate index, order from zero, decode each base64 data value, concatenate the bytes, verify their SHA-256 equals reportId, and parse the UTF-8 JSON. At most 100 parts, each holding 10 KB of decoded bytes. Retain incomplete groups across reconnect and use iac.events to recover missing parts. This keeps graph WebSocket frames below 32 KB without discarding report content.',eventExtension:{source:['lifecycle','application'],phase:['recovering','awaiting-recovery-approval','maintenance','readiness','runtime'],lifecycle:'Structured inspection, recovery plan/approval/action/result, maintenance request/review, readiness result or invocation correlation, or a documented fragment of that record. No application payloads or credentials.',correlationId:'Deployment/recovery operation by default; application invocation uses its actual graph correlation ID.',executionId:'Present for graph invocation diagnostics.',requestId:'Lambda runtime request ID when available; lifecycle.bridgeRequestId links the private bridge invocation.'}},
 logs:{bounds:'100 raw events/page, 80 KB/page, one-hour time window, seven-day lookback, at most 100 pages/query, 24-hour cursor lifetime. AWS next tokens remain server-side. Empty pages can have a continuation. Omitted arbitrary console records and truncation are explicit. Choose at most one requestId, invocationId or correlationId filter; a cursor preserves that filter and window.',format:{type:'graph.application.diagnostic',level:'ERROR',requestId:'context.awsRequestId',correlationId:'event.context.correlationId',error:{code:'INVARIANT_FAILED',message:'Describe the failed invariant; never log inputs, tokens, or personal records.'}},limitations:'Lambda START/END/REPORT, runtime exceptions and the declared diagnostic record shape are supported. User console payloads are excluded. A call rejected before Lambda execution has no Lambda request ID and is diagnosed through invocation events.'},
 readinessDeclaration:{property:'node.properties.iac.readiness',example:[{id:'backend-health',nodeUrl:'backend-health',field:'in',value:{action:'health'},description:'The node calls the application bridge and throws if backend invariants fail.'}],approval:'Declarations are included in the input digest. Execute one named check per call; all declared checks must pass for runtimeReadiness.state=verified. Results include execution and revision references.'},
 examples:[
  {tool:'iac.inspect',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack'}},
  {tool:'iac.recovery.plan',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',operationId:'01M4CSD7D7H7YM2HKY2Z5AJRHZ',idempotencyKey:'recovery-1'}},
  {human:'Review the recovery plan in the CloudFormation node and approve its recovery digest.'},
  {tool:'iac.status',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack'}},
  {tool:'iac.review',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',retryOf:'<current recovered operation ID>'}},
  {human:'Approve the new exact deployment digest in the graph.'},
  {tool:'iac.runtime.logs',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',logicalId:'Backend',correlationId:'<graph invocation correlation>'}},
  {tool:'iac.readiness',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',checkId:'backend-health',idempotencyKey:'health-1'}},
 ],
};
