import * as z from 'zod/v4';
const ID=z.string().regex(/^[A-Za-z0-9_.-]{1,64}$/),ULID=z.string().regex(/^[0-9A-HJKMNP-TV-Z]{26}$/);
const base={schemaVersion:z.literal(1),graphId:ID,nodeId:ID};
const prerequisite=z.object({code:z.string(),kind:z.string(),message:z.string()}).passthrough();
const resource=z.object({logicalId:z.string(),resourceType:z.string(),physicalId:z.string().optional(),physicalIdentity:z.string().optional(),status:z.string(),deletionPolicy:z.string(),definitionDigest:z.string(),ownershipVerified:z.boolean(),exists:z.boolean().optional(),orphaned:z.boolean().optional()}).passthrough();
const stack=z.object({name:z.string(),status:z.string(),ownership:z.enum(['verified','unverified','absent']),stackId:z.string().optional(),lastStackId:z.string().optional(),resources:z.array(resource)}).passthrough();
const nextActions=z.object({retryable:z.boolean(),automaticRetry:z.literal(false),blockingPrerequisites:z.array(prerequisite),actions:z.array(z.object({tool:z.string().optional(),action:z.string().optional(),allowed:z.boolean(),requiredApproval:z.string().nullable(),reason:z.string().optional()}).passthrough())});
const maintenanceConfiguration=z.object({configured:z.boolean(),mode:z.literal('record-and-verify-only'),executesAws:z.literal(false),approvalEffect:z.string(),administratorRequirement:z.string(),blocker:prerequisite.optional()}).passthrough();
const recoveryReadiness=z.object({state:z.enum(['review-available','blocked','not-required']),prerequisites:z.array(prerequisite),missingRoles:z.array(z.string()),executionAuthority:z.string(),requiredApproval:z.literal('human-exact-recovery-digest'),requiresPlatformAdmin:z.boolean()});
const inspection=z.object({version:z.number(),checkedAt:z.string(),graphId:ID,nodeId:ID,
 application:stack,guardrail:stack,
 roles:z.array(z.object({logicalId:z.string(),arn:z.string(),exists:z.union([z.boolean(),z.literal('unknown')]),matches:z.boolean()}).passthrough()),
 boundary:z.object({arn:z.string(),exists:z.union([z.boolean(),z.literal('unknown')])}).passthrough(),
 recoveryReadiness,blockers:z.array(prerequisite),canReview:z.boolean(),
 awsVerification:z.object({kind:z.literal('actual-read-and-assume-calls'),deploymentTested:z.literal(false),checks:z.array(z.object({component:z.string(),action:z.string(),resource:z.string(),result:z.enum(['succeeded','absent','failed']),code:z.string().optional(),error:z.any().optional()}).passthrough())}),
 maintenanceConfiguration:maintenanceConfiguration.optional(),historicalFailure:z.any().optional(),historyIsNotCurrentPermissionEvidence:z.literal(true).optional(),
}).passthrough();
const recoveryReview=z.object({version:z.string(),digest:z.string().regex(/^[a-f0-9]{64}$/),sourceOperationId:ULID,graphId:ID,nodeId:ID,
 preservesData:z.boolean(),prerequisites:z.array(prerequisite),ownershipEvidence:z.object({application:stack,guardrail:stack}),
 actions:z.array(z.object({kind:z.enum(['delete-stack','import-retained','reconcile-guardrails','continue-update-rollback','rollback-stack','release-operation']),target:z.enum(['guardrail','application','operation']),dataLoss:z.array(z.string()),retainIds:z.array(z.string()).optional(),preparation:z.object({kind:z.literal('owned-empty-stack'),templateDigest:z.string(),createsResources:z.literal(false),roleArn:z.string()}).optional(),resources:z.array(z.object({logicalId:z.string(),physicalId:z.string().optional(),physicalIdentity:z.string().optional(),resourceType:z.string().optional(),outcome:z.enum(['Already absent','Retain','Delete','Create from approved platform definition']).optional(),identifier:z.string().optional(),definitionDigest:z.string().optional()}).passthrough()).optional()}).passthrough()),
 approvalRequirements:z.object({kind:z.literal('infrastructure-recovery'),exactDigest:z.literal(true),platformAdministrator:z.literal(false),applicationDeployment:z.literal(false)}),approval:z.string(),
}).passthrough();
export const lifecycleResultSchemas={
 'iac.inspect':inspection.extend({operationId:ULID,nextActions}),
 'iac.recovery.plan':z.object({operationId:ULID,graphId:ID,nodeId:ID,action:z.literal('recover'),state:z.enum(['recovery-blocked','recovery-ready','recovery-requested','recovering','recovered','failed']),recoveryPlan:recoveryReview,inspection,expiresAt:z.number(),nextActions}).passthrough(),
 'iac.maintenance.request':z.object({digest:z.string(),state:z.string(),requirements:z.array(prerequisite),execution:z.object({mode:z.literal('record-and-verify-only'),executesAws:z.literal(false),approvalTriggersRelease:z.literal(false),recoveryApproved:z.literal(false),applicationDeploymentApproved:z.literal(false)}),administration:maintenanceConfiguration}).passthrough(),
};
export const lifecycleTools={
 'iac.inspect':{method:'inspect',write:false,description:'Read current AWS stack/resource ownership, retained resources, role/trust/boundary documents, actual read/assumption results and active operations. Historical failures, template validation and policy analysis are separate evidence. Never deploys or recovers.',schema:z.object({...base,operationId:ULID.optional()}).strict()},
 'iac.recovery.plan':{method:'plan',write:true,description:'Prepare an immutable recovery plan for an isolated failed deployment. Ownership, retention and AWS state select the bounded actions. Idempotency key is required; nothing executes until a human approves the exact recovery digest in the graph. Recovery does not approve application deployment.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID,idempotencyKey:z.string().regex(/^[A-Za-z0-9_.-]{1,128}$/),allowDataLoss:z.boolean().optional()}).strict()},
 'iac.maintenance.request':{method:'maintenance',write:true,description:'Record a graph-visible request for current platform prerequisites. This is record-and-verify-only: neither requesting nor approving it executes AWS changes or triggers a platform release. The response explains missing PLATFORM_ADMIN_SUBS configuration. Ordinary graph recovery approval does not require platform-admin membership.',schema:z.object({...base,agentSessionId:ID.optional(),operationId:ULID}).strict()},
 'iac.runtime.logs':{method:'runtimeLogs',write:false,description:'Read bounded, redacted Lambda diagnostics for a logical function owned by an approved application stack. Window <=1 hour within 7 days; opaque cursors preserve filters. Same records are published to the graph bus and iac.events. Arbitrary console payloads and account-wide log access are excluded.',schema:z.object({...base,operationId:ULID.optional(),logicalId:z.string().regex(/^[A-Za-z0-9]{1,64}$/),startTime:z.iso.datetime().optional(),endTime:z.iso.datetime().optional(),invocationId:ULID.optional(),requestId:z.string().regex(/^[A-Za-z0-9_.:-]{1,128}$/).optional(),correlationId:z.string().regex(/^[A-Za-z0-9_.:-]{1,128}$/).optional(),cursor:z.string().max(2048).optional(),limit:z.number().int().min(1).max(100).optional()}).strict()},
 'iac.readiness':{method:'readiness',write:true,description:'Run one readiness check declared in the approved deployment through graph.invoke. Requires graph execution authority. Reusing its idempotency key returns the existing run, never repeats side effects. Readiness is separate from deployment completion and multiplayer verification.',schema:z.object({...base,agentSessionId:ID.optional(),checkId:ID,idempotencyKey:z.string().regex(/^[A-Za-z0-9_.-]{1,128}$/)}).strict()},
};
export const lifecycleContract={
 uri:'plastic://schema/1/lifecycle',version:'1.2.1',
 resultSchemas:Object.fromEntries(Object.entries(lifecycleResultSchemas).map(([name,schema])=>[name,z.toJSONSchema(schema)])),
 tools:Object.fromEntries(Object.entries(lifecycleTools).map(([name,tool])=>[name,{description:tool.description,inputSchema:{...z.toJSONSchema(tool.schema),...(name==='iac.runtime.logs'?{allOf:[{not:{required:['requestId','invocationId']}},{not:{required:['requestId','correlationId']}},{not:{required:['invocationId','correlationId']}}]}:{})}}])),
 automaticApproval:{enabledBy:'Explicit human opt-in with warning in the graph editor. Off by default; reset on reload or graph change. MCP cannot enable it or approve.',eligibility:'iac.status.automaticApproval reports allowed and reason. The server rejects approvalMode=automatic for stack deletion, resource removal/replacement, uncertain deployment changes, rollback recovery and any data loss. Only current unexpired exact digests can be approved.',audit:'approval.mode and recoveryApproval.mode identify manual or automatic approval in durable status and bus events. This mode does not accept graph proposals or create reviews.'},
 permissions:{inspect:['graph:read','iac:read-status'],plan:['graph:read','iac:propose'],recoveryApproval:'Authenticated human with graph read and iac:approve, through the graph UI; exact recovery digest required.',logs:['graph:read','iac:read-status','graph:observe','graph:inspect-payloads'],readiness:['graph:read','iac:read-status','graph:execute','graph:observe'],maintenanceReview:'Human with policy:admin whose verified sub is explicitly configured in PLATFORM_ADMIN_SUBS. Agents, delegations and ordinary graph ownership cannot grant platform administration.'},
 states:{recovery:['recovery-blocked','recovery-ready','recovery-requested','recovering','recovered','failed'],maintenance:['requested','approved-awaiting-platform-release','verification-blocked','verified'],runtime:['pending','running','verified','failed'],deployment:'Existing planning → awaiting-review → apply-requested → applying → succeeded/failed lifecycle remains separate.'},
 evidence:{historical:'iac.status preserves the original failure even after permissions are corrected.',inspection:'iac.inspect reports checkedAt, current application/guardrail inventories and ownership evidence, current policy analysis, actual AWS read/STS calls, and the original workflow state.',policy:'Document analysis is not IAM simulation and neither is proof that CloudFormation will succeed. SCPs, session policies and service checks can deny real operations.',readiness:'A declared check node must assert application-specific health. The platform records completed execution, zero execution errors and zero denied effects. This does not prove real multiplayer behavior.'},
 recovery:{freshness:'Plans expire after 15 minutes. Digest binds source operation, namespace, template input digest, resource IDs/states/retention, approved guardrail definition, actions, prerequisites and data-loss choice. Observation timestamps and original error prose are excluded from the freshness fingerprint.',selection:'UPDATE_ROLLBACK_FAILED continues rollback without skipping resources. UPDATE_FAILED rolls back only with reviewed retention/data-loss implications. Failed creates/deletes remove only the owned failed stack, preserving retained data; RetainResources is used only for DELETE_FAILED. Retained resources are imported into the same namespace before names can be reused. import-retained.preparation discloses a fixed empty stack with no created resources: establish the assigned role and ownership tags first, then IMPORT without changing stack settings. Interrupted preparation preserves archived ownership evidence and needs a fresh approval; it does not silently discard retained names. Unsupported imports remain an explicit prerequisite.',isolation:'Guardrail templates come only from platform source. Imports require CloudFormation ownership evidence, not just matching names. Unrelated resources, shared deployment policies, extra role policies and unverified orphans cannot be changed by application recovery.',concurrency:'Deployment and recovery share one CAS stack fence. Duplicate recovery keys return the same operation; reuse for different input is refused. Worker leases plus deterministic AWS request tokens handle duplicate delivery. A stale plan or lost fence cannot execute.',retry:'No automatic retry of deterministic failures. After recovered, call iac.review with retryOf equal to the current recovery operation. Replacement operations retain previousOperationId and original evidence. Old approvals are invalidated. Human deployment approval itself triggers execution.'},
 incompleteGuardrails:{absence:'IAM NoSuchEntity/NoSuchEntityException means absent, independent of error wording. AccessDenied, network failures, timeouts and unsupported errors leave exists="unknown" and block recovery. Stack and workflow absence use their own documented service errors.',
  transientChecks:'Read-only inspection serializes IAM calls and retries transient throttling/transport failures with jitter, at most three attempts per call within the inspection deadline. Exhaustion returns AWS_CHECK_RETRYABLE, kind=transient, retryable=true and retryAfterMs; deadline exhaustion returns INSPECTION_INCOMPLETE. Readiness remains unverified, but these conditions alone do not require a platform administrator or a maintenance request. Wait, repeat iac.inspect, then prepare a fresh plan if needed. This does not retry a deployment or recovery mutation.',
  authority:'An owned failed guardrail stack can be deleted and its retained boundary imported before platform-approved roles are recreated. These actions use the platform worker and guardrail service role, not the missing per-stack worker or execution role. Per-stack role assumption is verified after restoration.',
  preservation:'The plan lists already-absent roles separately from resources to delete and retained resources to import. IAM physical identities and boundary contents/consumers are rechecked before deleting or importing guardrails. Imported resources remain retained. In DELETE_FAILED only, confirmed-absent owned role records can be included in RetainResources to skip their deletion handlers; they are not imported as live resources. No arbitrary existing-resource adoption is supported.',
  limitation:'A stable guardrail stack with out-of-band deleted roles still recorded in its template returns GUARDRAIL_ROLE_RECREATE_UNSUPPORTED. An unchanged CloudFormation update cannot recreate those roles, and private repair has no CreateRole permission. A separately reviewed platform replacement procedure is required. Failed-creation recovery and boundary-only imports do not have this limitation.',
  approval:'Prepare a NEW iac.recovery.plan from the current operation with a new idempotencyKey after a platform fix; an existing blocked plan never silently becomes approved. A graph human with iac:approve reviews its exact digest. PLATFORM_ADMIN_SUBS is not required for ordinary graph-owned recovery.',
  evidence:'inspection.recoveryReadiness reports review-available/blocked/not-required, missingRoles, prerequisites, executionAuthority, requiredApproval and requiresPlatformAdmin. This describes recovery planning, not application deployability. historicalFailure and historicalFailureOperationId preserve old errors separately from current awsVerification.'},
 maintenance:{mode:'record-and-verify-only',executesAws:false,approvalTriggersRelease:false,
  bootstrap:'A platform administrator must review and deploy shared permission changes through the platform release process. PLATFORM_ADMIN_SUBS configures a separate human maintenance reviewer. Empty configuration returns PLATFORM_ADMIN_NOT_CONFIGURED in maintenanceConfiguration; graph ownership does not implicitly enable it. This configuration is not a prerequisite for graph-owned recovery.',
  approval:'A maintenance request and its human approval only record the reviewed prerequisite. An administrator releases any necessary platform change separately, then verifies current evidence in the graph. They never authorize recovery or application deployment.',
  response:{execution:{mode:'record-and-verify-only',executesAws:false,approvalTriggersRelease:false,recoveryApproved:false,applicationDeploymentApproved:false},administration:{configured:false,mode:'record-and-verify-only',executesAws:false,blocker:{code:'PLATFORM_ADMIN_NOT_CONFIGURED',kind:'configuration',component:'platform-authorization'}}}},
 resultFields:{inspection:{roles:'Array of {logicalId,arn,exists:true|false|"unknown",matches,policyDigest?,trustDigest?,boundary?}. Missing roles have exists=false; they are not permission denials.',recoveryReadiness:'{state:"review-available"|"blocked"|"not-required",prerequisites,missingRoles,executionAuthority,requiredApproval:"human-exact-recovery-digest",requiresPlatformAdmin}',awsVerification:'{kind:"actual-read-and-assume-calls",checks:[{component,action,resource,result:"succeeded"|"absent"|"failed",code?,error?}],deploymentTested:false}',maintenanceConfiguration:'{configured,mode:"record-and-verify-only",executesAws:false,approvalEffect,administratorRequirement,blocker?}'},
  recoveryPlan:{approvalRequirements:{kind:'infrastructure-recovery',exactDigest:true,platformAdministrator:false,applicationDeployment:false},actions:'Existing delete-stack/import-retained/reconcile-guardrails actions. Resource outcomes include "Already absent", "Retain", "Delete", and "Create from approved platform definition". An import includes physicalIdentity when AWS provides an immutable IAM identity.'}},
 observations:{transport:'deployment.progress records on the existing graph-notify bus, iac.events and observations.watch carry the same redacted lifecycle field. Status also includes nextActions, inspection, recoveryPlan, recoveryApproval, recoveryOutcomes, maintenance and runtimeReadiness. Existing cursors, stable IDs, outbox, deduplication and history apply.',fragmentation:'Reports above 14 KB use lifecycle.fragment={reportId,index,count,encoding:"base64-json-utf8",data}. Group by operationId and reportId; deduplicate index, order from zero, decode each base64 data value, concatenate the bytes, verify their SHA-256 equals reportId, and parse the UTF-8 JSON. At most 100 parts, each holding 10 KB of decoded bytes. Retain incomplete groups across reconnect and use iac.events to recover missing parts. This keeps graph WebSocket frames below 32 KB without discarding report content.',eventExtension:{source:['lifecycle','application'],phase:['recovering','awaiting-recovery-approval','maintenance','readiness','runtime'],lifecycle:'Structured inspection, recovery plan/approval/action/result, maintenance request/review, readiness result or invocation correlation, or a documented fragment of that record. No application payloads or credentials.',correlationId:'Deployment/recovery operation by default; application invocation uses its actual graph correlation ID.',executionId:'Present for graph invocation diagnostics.',requestId:'Lambda runtime request ID when available; lifecycle.bridgeRequestId links the private bridge invocation.'}},
 logs:{bounds:'100 raw events/page, 80 KB/page, one-hour time window, seven-day lookback, at most 100 pages/query, 24-hour cursor lifetime. AWS next tokens remain server-side. Empty pages can have a continuation. Omitted arbitrary console records and truncation are explicit. Choose at most one requestId, invocationId or correlationId filter; a cursor preserves that filter and window.',format:{type:'graph.application.diagnostic',level:'ERROR',requestId:'context.awsRequestId',correlationId:'event.context.correlationId',error:{code:'INVARIANT_FAILED',message:'Describe the failed invariant; never log inputs, tokens, or personal records.'}},limitations:'Lambda START/END/REPORT, runtime exceptions and the declared diagnostic record shape are supported. User console payloads are excluded. A call rejected before Lambda execution has no Lambda request ID and is diagnosed through invocation events.'},
 readinessDeclaration:{property:'node.properties.iac.readiness',example:[{id:'backend-health',nodeUrl:'backend-health',field:'in',value:{action:'health'},description:'The node calls the application bridge and throws if backend invariants fail.'}],approval:'Declarations are included in the input digest. Execute one named check per call; all declared checks must pass for runtimeReadiness.state=verified. Results include execution and revision references.'},
 examples:[
  {tool:'iac.inspect',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack'}},
  {result:{application:{status:'NOT_CREATED'},guardrail:{status:'ROLLBACK_FAILED',ownership:'verified'},roles:[{logicalId:'WorkerRole',exists:false,matches:false},{logicalId:'ExecutionRole',exists:false,matches:false}],boundary:{exists:true,matches:true},recoveryReadiness:{state:'review-available',missingRoles:['WorkerRole','ExecutionRole'],prerequisites:[],requiresPlatformAdmin:false},awsVerification:{kind:'actual-read-and-assume-calls',deploymentTested:false},canReview:false},note:'Missing roles are restored by approved recovery. canReview=false refers to application deployment; policy analysis is not evidence of successful AWS execution.'},
  {tool:'iac.recovery.plan',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',operationId:'01M4C000000000000000000000',idempotencyKey:'recovery-1'}},
  {human:'Open Recovery beside the CloudFormation notifications in the lower system bar, review the affected stack/resources, and approve its exact recovery digest.'},
  {tool:'iac.status',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack'}},
  {tool:'iac.review',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',retryOf:'<current recovered operation ID>'}},
  {human:'Approve the new exact deployment digest in the graph.'},
  {tool:'iac.runtime.logs',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',logicalId:'Backend',correlationId:'<graph invocation correlation>'}},
  {tool:'iac.readiness',arguments:{schemaVersion:1,graphId:'example',nodeId:'stack',checkId:'backend-health',idempotencyKey:'health-1'}},
 ],
};
